#!/usr/bin/env python
#
# Script to build the files found in this directory.
#------------------------------------------------------------------------------
import os
Import('stntuple_env')
Import('stntuple_helper')
#------------------------------------------------------------------------------
# 2016-10-10: add ROOT 'EG' library after 'Physics' library
#------------------------------------------------------------------------------
def local_build():

    local_env = stntuple_env.Clone()
    rootlibs  = local_env['ROOTLIBS']

    if ( not ("MathMore" in rootlibs)): rootlibs.insert(rootlibs.index("MathCore")+1,"MathMore");

    debug  = False
    helper = stntuple_helper(local_env,debug);

    dict_skip_list = []

    helper.handle_dictionaries(".hh",dict_skip_list);

    list_of_cc_files =  Glob('*.cc', strings=True);
    skip_list        = [ ]

    stntuple_libs    = [ 'Stntuple_val', 'Stntuple_alg' ]

    libs             = stntuple_libs + [ rootlibs ];

    helper.build_libs(list_of_cc_files, skip_list,libs);
#------------------------------------------------------------------------------
local_build()
