# hit <TAB> to expand and collapse the menues
* ------------------------------------------------------------------------------
* what is STNTUPLE                                                           

  STNTUPLE is two things:

  - an ntuple data format
  - a light-weight interactive ntuple analysis framework, used for many years by the CDF experiment at Fermilab 
    and ported to Mu2e.
    The framework supprots multiple job configurations, it is interfaced to the data handling system and allows to run 
    analysis jobs of any complexity, interactively and on the GRID.

  STNTUPLE development is based on the following assumptions:

  - in any experiment, over time, ntuples become large. De-facto, they become mini-DST's.
  - Ntuple datasets also become large, one needs a way to share them and store them in the data handling system
  - "Click-on-TNtuple"-based mode doesn't work for publication-level analysis. 
     To be able to efficiently re-submit a job and to deal with multiple jobs 
     one needs a framework. 
     For reproducibility, analysis jobs should be configured and driven by scripts
  - analysis code quickly becomes rather sophisticated. 
    It can't be used in interpreted mode - has to be compiled
  - HEP uses C++ for compiled code. Using one language is less expensive than two.
    Thus all scripting, and the needed level of scripting is rather simple, is done using ROOT C++ 
    interpreting capabilities
  - an HEP analysis can be competed and publish using ~5% of C++ functionality, without any disadvantages.
    Therefore STNTUPLE C++ is, by design, a "simple" , C-style, C++, which doesn't require any knowledge 
    of advanced features of the language.

  - lets keep it simple :) 

* [[file:./how-to-build.org][how to build Stntuple libraries]]
* [[file:how-to-make-first-stntuple.org][how to make first Stntuple]] 
* [[file:stnana.org][stnana]] - STNTUPLE analysis framework                                       
* [[file:stntuple-datasets.org][STNTUPLE datasets]]
* STNTUPLE [[file:how-tos.org][how-to's]]                                                                    
* ------------------------------------------------------------------------------
* more technical details
* ------------------------------------------------------------------------------
* [[file:sample-fcl-files.org][Example FCL files]]                                                            
* [[file:package-organization.org][package organization]]                                                          
* [[file:data_blocks.org][Stntuple data blocks]]
* [[file:track_id.org][TStnTrackID]]
* ------------------------------------------------------------------------------
