#!/bin/bash
#------------------------------------------------------------------------------
# BUILD_BASE doesn't replace the SATELLITE_RELEASE, need both
#------------------------------------------------------------------------------
base=$MUSE_WORK_DIR/build

echo Stntuple::build_config_muse:000: MUSE_VERBOSE:.$MUSE_VERBOSE.

if [ ".$MUSE_VERBOSE" != ".0" ] ; then echo Stntuple::build_config_muse:001: $\0:$0 : \$PWD=$PWD  \$base=$base ; fi

# pkg=`pwd | awk -F / '{print $(NF-1)}'`
pkg=`echo $0 | awk -F / '{print $(NF-2)}'`

        pkg_dir=$MUSE_WORK_DIR/$pkg
pkg_include_dir=$base/include/$pkg

echo Stntuple::build_config_muse: package=$pkg

list_of_subpackages="alg ana base geom gui loop mod obj print val"
#------------------------------------------------------------------------------
# package and its subpackages
#------------------------------------------------------------------------------
if [ ! -d $pkg_include_dir ] ; then
    if [ $MUSE_VERBOSE != 0 ] ; then echo Stntuple::build_config_muse: pwd=$pwd ; creating $base/include/$pkg ; fi
    mkdir -p $pkg_include_dir
fi
#------------------------------------------------------------------------------
# make symbolic links local, as they are 
#------------------------------------------------------------------------------
for d in $list_of_subpackages ; do
    if [[ -e $base/include/$pkg ]] && [[ ! -e $base/include/$pkg/$d ]] ; then 
	cmd="ln -s ../../../$pkg/$d/$d $pkg_include_dir/$d"
	if [ $MUSE_VERBOSE != 0 ] ; then echo `pwd`$0 : executing: $cmd ; fi
	$cmd
    fi
done
#------------------------------------------------------------------------------
# make sure $WORK_DIR/site_scons directory exists
# SCons-related things: executed from Stntuple
# execution in Stntuple
#------------------------------------------------------------------------------
if [ ! -d $MUSE_WORK_DIR/site_scons ] ; then mkdir $MUSE_WORK_DIR/site_scons ; fi
cp -u $pkg_dir/scripts/stntuple_site_init.py       $MUSE_WORK_DIR/site_scons/.
cp -u $pkg_dir/scripts/stntuple_helper.py          $MUSE_WORK_DIR/site_scons/.
#------------------------------------------------------------------------------
# .rootrc and rootlogon.C could be modified by the user, copy them just once
#------------------------------------------------------------------------------
if [ ! -f $MUSE_WORK_DIR/.rootrc     ] ; then cp $pkg_dir/scripts/.rootrc     $MUSE_WORK_DIR/. ; fi
if [ ! -f $MUSE_WORK_DIR/rootlogon.C ] ; then cp $pkg_dir/scripts/rootlogon.C $MUSE_WORK_DIR/. ; fi
